export {AdToFavsBTN} from './addToFav'
export {PlayBtn} from './play'
export {BackBtn} from './toBack'
export {InfMovBtn} from './infomovie'
export {SearchButton} from './searchbtn'
export {RemoveFav} from './removefav'